
version: "2"

services:

# #####################################################
# Base services
  base_integration:
    mem_limit: 2g
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile.assemble

  base_volume:
    mem_limit: 1g
    image: ubuntu
    entrypoint: /bin/true

# #####################################################
# Integration services
  assembler:
    extends:
      service: base_integration
    command: /os/bin/assemble.sh
    depends_on:
      - source
      - target
    volumes_from:
      - source
      - target
    environment:
      - OS_TARGET=${OS_TARGET}
      - OS_APP=${OS_APP}
      - OS_BUILD=${OS_BUILD}
      - OS_EXTRAS=${OS_EXTRAS}

  cleaner:
    extends:
      service: base_integration
    command: /os/bin/clean.sh
    depends_on:
      - source
      - target
    volumes_from:
      - source
      - target
    environment:
      - OS_TARGET=${OS_TARGET}
      - OS_APP=${OS_APP}
      - OS_BUILD=${OS_BUILD}
      
  watcher:
    extends:
      service: base_integration
    command: /os/bin/watch.sh
    hostname: bipper
    depends_on:
      - source
      - target
    volumes_from:
      - source
      - target
    network_mode: host
    ports:
      - 8100:8100
    environment:
      - OS_TARGET=${OS_TARGET}
      - OS_APP=${OS_APP}
      - OS_BUILD=${OS_BUILD}
      - WATCH_DO_CLEAN=${WATCH_DO_CLEAN}
      
# #####################################################
# Volume services
  source:
    extends:
      service: base_volume
    volumes:
      -  ../../src:/os/build/src
      -  ../../etc:/os/build/etc
      -  ../../test:/os/build/test
      -  ../../extras:/os/build/extras

  target:
    extends:
      service: base_volume
    volumes:
      -  ../../.dist:/os/target